---
plugin: community.digitalocean.digitalocean
api_token: '{{ lookup("env", "DOC_RO_API_KEY") }}'
attributes:
  - id
  - name
  - image
  - networks
  - tags
  - status
keyed_groups:
  - key: do_tags | lower
    prefix: ''
    separator: ''
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
  distro: do_image.distribution | lower
