---
- name: archive images to transfer
  hosts: eve-ng
  gather_facts: false

  vars:
    create_archive: false
    archive_local_dest: ../.local/images.tar.gz
    archive_remote_dest: /opt/unetlab/addons/images.tar.gz

  tasks:
    - name: check if archive exists
      stat:
        path: "{{ archive_local_dest }}"
      register: stat_archive
      delegate_to: localhost
      run_once: true

    - name: compress image directory
      community.general.archive:
        path: ../../../eve-ng_images
        dest: "{{ archive_local_dest }}"
        format: gz
      delegate_to: localhost
      run_once: true
      when: (create_archive|bool) or not (stat_archive.stat.exists)

    - name: transfer images
      ansible.builtin.copy:
        src: ../.local/images.tar.gz
        dest: "{{ archive_remote_dest }}"

    - name: Extract images
      ansible.builtin.unarchive:
        src: "{{ archive_remote_dest }}"
        dest: /opt/unetlab/addons/
        remote_src: true

    - name: remove archive
      file:
        path: "{{ archive_remote_dest }}"
        state: absent
